# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: tmeralus
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_repositories: 100 
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          # The repositories traffic plugin displays the number of page views across your repositories.
          plugin_traffic: yes
          # The stargazers plugin displays your stargazers evolution across all of your repositories over the last two weeks.
          plugin_stargazers: yes

          # Recently starred repositories
          #plugin_stars: yes
          #plugin_stars_limit: 5

          # The rss plugin displays feed from my blog
          plugin_rss: yes
          plugin_rss_source: https://meralus.com/feed.xml
          plugin_rss_limit: 6
          
          plugin_tweets: yes
          plugin_tweets_limit: 3
          plugin_tweets_user: techgameteddy
